version: '3'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
      - ./data:/import_data
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1-${ARCH}
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=your_password_here
      - xpack.security.enabled=true
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data
